---
title: "Daily Translation: Working Late at the Office"
author: "Ryan Sun"
date: "2026-08-26"
categories: [English Learning, Daily Translation]
---

## 中文原文

工作日晚上公司有紧急工作需要处理，你不得不留下来加班。办公室其他人陆续下班走了，只剩下你。你对着电脑处理报表，中间泡了一杯速溶咖啡提神。一直忙到快九点才做完手上的活，收拾好东西关灯锁门，拖着疲惫的身体坐地铁回家。

## My translation

I had emergent work to deal with during the evening of workdays, so I have to work overtime.

Other people went off, only myself left.

I processed worksheet with the computer, during which I had a cup of coffee for refreshment.

Until around 9 pm I finally finished my work, I cleaned up my stuff, turned down the light and locked the door, then went home with very tired body by subway.

## Revised version

I got stuck with some urgent work on a weekday evening, so I had to stay late at the office.

One by one, my colleagues headed home, and soon I was the only one left.

I sat at my computer going through reports and made myself a cup of instant coffee to keep myself going.

I didn’t wrap up my tasks until almost 9 p.m. I packed up my belongings, switched off the lights and locked up, then dragged myself home on the subway.
