---
title: "Daily Translation: An Early Night Ruined by Urgent Work"
author: "Ryan Sun"
date: "2026-09-30"
categories: [English Learning, Daily Translation]
---

## 中文原文
你这周一直很忙，打算今晚早点休息。下班回家后，你简单煮了晚饭，洗完碗，准备上床。刚关灯躺下，突然收到领导发来的消息，有一份紧急文件需要你今晚修改并且发送。你只好重新打开电脑，坐在书桌前处理。等全部弄完，已经很晚，原本早睡的计划泡汤了

## My translation
I was busy this week, so I'd planned to sleep early tonight.
After I finished work and headed home, I made myself a simple dinner. then washed the dishes and was about to go to the bed.
Suddenly, I got messages from the team leader, saying that I need to revise an urgent file and send it back to him.
I had to re-open my laptop and process the work at the desk.
When all thing was done, it was already very late. My plan of early-sleeping screwed.

## Revised version
I'd been busy this week, so I planned to go to bed early tonight.
After work, I headed home, made myself a simple dinner, then washed the dishes.
I was about to go to bed when I suddenly received messages from the team leader.
He said I needed to revise an urgent document and send it back to him.
I had to reopen my desktop and get down to the work at my desk.
When everything was finished, it was already very late. My plan to get an early night was completely screwed up.

## Key phrases
- go to bed, 没有the
- 连续用动词来表达接连不断的动作
- get down to the work，开始着手做事
- get an early night，早睡
- was screwed up，一般用被动表示泡汤
