---
title: "Daily Translation: Work Interrupting an Evening Show"
author: "Ryan Sun"
date: "2026-09-16"
categories: [English Learning, Daily Translation]
---

## 中文原文
晚上在家，你本来想看一集剧集放松。刚点开视频，突然收到好几条工作消息。你只好停下看剧，花了不少时间处理工作，等忙完之后已经没有精力看剧了

## My translation
I was at home tonight. I'd planned to watch an episode of TV for relax.
By the time I opened the video, some work messages came in.
I had to stop, and took quiet a few time to handel the work.
When all things were done, I was already too exhausted to watching the TV.

## Revised version
I was at home tonight. I'd planned to watch an episode of a show to relax.
Right as I pulled up the video, several work messages popped up.
I had to stop and spent quiet a bit of time handelling those work tasks.
Once I finished everything, I was far too worn out to watch anything.

## Key phrases
- episode of a show, 没有episode of TV这种说法
- pull up the video, 点开视频
- messages popped up, 消息弹出来
- quiet a bit of time, a few time是错误的，time是不可数
- worn out, 疲惫不堪，口语中代替exhausted
