---
title: "Daily Translation: Getting Distracted by Old Photos"
author: "Ryan Sun"
date: "2026-09-28"
categories: [English Learning, Daily Translation]
---

## 中文原文
昨天下午，我打算整理电脑里的照片文件夹。里面存了很多旅行、和朋友聚会的照片。本来只想分类归档，结果看着旧照片，忍不住一张一张仔细翻看。不知不觉花了两个多小时。等回过神来，我才发现原本计划要完成的工作一点都没动，只好晚上加班。

## My translation
Yesterday afternoon, I tried to sort out the picture folders in my computer, in which there were many trip and gathering photoes.
I'd planned to only categorize and archive those pictures, but with those old pictures, I couldn't stand with looking at them deliberately.
I was so focused that When I realized it almost took me two hours.
The work that I'd planned to fininsh hadn't been done at all.
I had to work overtime at night.

## Revised version
Yesterday afternoon, I tried to sort out the photo folders on my computer. They contained lots of pictures from trips and get-togethers.
I only meant to categorize and archive those photos, but once I saw these old shots, I couldn't help looking through them.
I got so absorbed that before I knew it, it had taken me almost two hours.
The task I'd planned to finish hadn't been touched at all.
I ended up having to work overtime that night.

## Key phrases
- meant to，本来想
- but once,但是
- can't help doing，忍不住做
- got so absorbed
- before I knew it，不知不觉
- ended up
