---
title: "Daily Translation: Saving a Dish from Burning"
author: "Ryan Sun"
date: "2026-09-13"
categories: [English Learning, Daily Translation]
---

## 中文原文
下班之后你打算在家做饭。你去菜市场买好了蔬菜和肉。回到厨房开始处理食材。炒菜的时候手机弹出几条工作消息，你分心看了一会儿。结果锅里的菜差点烧焦。你赶紧调小炉火，不停翻炒，总算挽救回来。

## My translation
I decided to make dinner at home after work.
I bought vegetables and meat at the market, then went back kitchen to process the ingridents.
While I was frying, my phone poped out several work messages, so I took some time to check.
As a result, the dish in the pot was almost burnt out. I had to turn down the stove and keep stiring.
Luckily, I rescued my meal at the end.

## Revised version
I decided to cook dinner at home after work.
I bought vegetables and meat at the market, then headed back to the kitchen to prep the ingredients.
While I was stir-frying, several work messages poped up on my phone, so I spent a moment checking them.
As as result, the dish in the pot almost got burnt.
I quickly turned down the heat and kept stirring.
Thankfully, I saved the meal in the end.

## Key phrases
- headed back to, 'went back kitchen'是典型的中式表达，要舍弃这种思维
- prep the ingredients, 比‘process the ingredients'地道很多
- stir-frying，炒菜，看似日常，但真的没碰到过
- poped up on the phone, 更地道
- got burnt，菜烧焦了，'burnt out'多指机器烧坏，人心力耗尽
- turn down the heat，把火关小，'stove'是炉子是一整套器具
- in the end, 固定搭配
