---
title: "Daily Translation: Forgetting a Wallet at the Supermarket"
author: "Ryan Sun"
date: "2026-09-27"
categories: [English Learning, Daily Translation]
---

## 中文原文
今天下班之后，你想去超市买食材准备做晚餐。你推了购物车，挑好了蔬菜、鸡蛋和一块牛排。排队结账的时候，你才想起忘记带钱包。手机里的支付软件也因为网络太差打不开。没办法，只能把挑好的东西放回货架，空手离开超市

## My translation
After finishing work today, I went to the supermarket to buy ingredients for dinner.
I got a shopping cart, and picked out vegetables, eggs and a steak.
Only when I waited in line for the checkout did I realize I forgot to bring my wallet.
The online paying app on my phone was out of work due to the bad internet.
I had to put the picked things back to the shelf, and left the supermarket with nothing.

## Revised version
After work today, I headed to the supermarket to buy ingredients for dinner.
I grabbed a shopping cart and picked out vegetables, eggs and a steak.
It was only when I waited in the checkout line that I realized I'd forgoteen my wallet.
The payment app on my phone wasn't working because of the poor internet connection.
I had to put all the items back on the shelves and leave the supermarket empty-handed.

## Key phrases
- grab, 好用的一个动词
- it was only when ... that ..., 干什么什么事情的时候突然想起来
- wait in the checkout line, 排队结账
- forgot my wallet, 不需要加to bring my
- payment app，支付软件，有名词形式的情况下不用ing做名词
- all the items指代更清楚
- on the shelf
- empty-handed，空手离开
